# Usamos la imagen oficial de Node.js
FROM node:18-alpine

# Creamos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos de configuración
COPY package.json package-lock.json ./

# Instalamos todas las dependencias, incluyendo las de desarrollo
RUN npm install --include=dev

# Copiamos el resto del código
COPY . .

# Exponemos el puerto 3000
EXPOSE 3000

# Ejecutamos la aplicación con nodemon
CMD ["npm", "run", "dev"]
